#!/bin/sh /etc/rc.common
# Copyright (C) 2013 OpenWrt.org

START=60
STOP=60
start() {
         telnetd -l /bin/ash
        # commands to launch application
}

stop() {
        killall telnetd
        # commands to kill application
}
